name: windows

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                os: [windows-latest]
                platform: [x64]
                build_type: [Debug, Release]

        runs-on: ${{matrix.os}}

        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: recursive

            - name: Create Build Environment
              run: cmake -E make_directory ${{github.workspace}}/build

            - name: Configure
              shell: bash
              working-directory: ${{github.workspace}}/build
              env:
                  CXX: ${{matrix.cxx}}
              run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} $GITHUB_WORKSPACE

            - name: Build
              shell: bash
              working-directory: ${{github.workspace}}/build
              run: time cmake --build . --config ${{matrix.build_type}}

